/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ClientTalentRouteImport } from './routes/client.talent'
import { Route as ClientPostJobRouteImport } from './routes/client.post-job'
import { Route as ClientPayoutsRouteImport } from './routes/client.payouts'
import { Route as ClientProjectsJobIdRouteImport } from './routes/client.projects.$jobId'
import { Route as ClientDisputesNewRouteImport } from './routes/client.disputes.new'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const ClientTalentRoute = ClientTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPostJobRoute = ClientPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPayoutsRoute = ClientPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProjectsJobIdRoute = ClientProjectsJobIdRouteImport.update({
  id: '/projects/$jobId',
  path: '/projects/$jobId',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDisputesNewRoute = ClientDisputesNewRouteImport.update({
  id: '/disputes/new',
  path: '/disputes/new',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/client/payouts': typeof ClientPayoutsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/talent': typeof ClientTalentRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/client/': typeof ClientIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/client/payouts': typeof ClientPayoutsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/talent': typeof ClientTalentRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/client': typeof ClientIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/client/payouts': typeof ClientPayoutsRoute
  '/client/post-job': typeof ClientPostJobRoute
  '/client/talent': typeof ClientTalentRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/client/': typeof ClientIndexRoute
  '/client/disputes/new': typeof ClientDisputesNewRoute
  '/client/projects/$jobId': typeof ClientProjectsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/client/payouts'
    | '/client/post-job'
    | '/client/talent'
    | '/jobs/$jobId'
    | '/client/'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/client/payouts'
    | '/client/post-job'
    | '/client/talent'
    | '/jobs/$jobId'
    | '/client'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/wallet'
    | '/client/payouts'
    | '/client/post-job'
    | '/client/talent'
    | '/jobs/$jobId'
    | '/client/'
    | '/client/disputes/new'
    | '/client/projects/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/client/talent': {
      id: '/client/talent'
      path: '/talent'
      fullPath: '/client/talent'
      preLoaderRoute: typeof ClientTalentRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/post-job': {
      id: '/client/post-job'
      path: '/post-job'
      fullPath: '/client/post-job'
      preLoaderRoute: typeof ClientPostJobRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payouts': {
      id: '/client/payouts'
      path: '/payouts'
      fullPath: '/client/payouts'
      preLoaderRoute: typeof ClientPayoutsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/projects/$jobId': {
      id: '/client/projects/$jobId'
      path: '/projects/$jobId'
      fullPath: '/client/projects/$jobId'
      preLoaderRoute: typeof ClientProjectsJobIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/disputes/new': {
      id: '/client/disputes/new'
      path: '/disputes/new'
      fullPath: '/client/disputes/new'
      preLoaderRoute: typeof ClientDisputesNewRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface ClientRouteChildren {
  ClientPayoutsRoute: typeof ClientPayoutsRoute
  ClientPostJobRoute: typeof ClientPostJobRoute
  ClientTalentRoute: typeof ClientTalentRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientDisputesNewRoute: typeof ClientDisputesNewRoute
  ClientProjectsJobIdRoute: typeof ClientProjectsJobIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientPayoutsRoute: ClientPayoutsRoute,
  ClientPostJobRoute: ClientPostJobRoute,
  ClientTalentRoute: ClientTalentRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientDisputesNewRoute: ClientDisputesNewRoute,
  ClientProjectsJobIdRoute: ClientProjectsJobIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
